### ISSUE TITLE
Design/Code Review 1

### ISSUE THREAD

**Issue by cvang13-madisoncollege** [kileader/Budget-Game-Rankings#5]
# Design/Code Review 1

### Reviewer: Christopher Vang

|Item |Considerations| Comments/Suggestions|
|--------|---------|---|
|||Reviewer comments and suggestions go here. EVERY item should have *at least* one "kudos" and one suggestion for improvement|
|**Problem Statement**|1. Accurately describes the project's purpose.<br> 2. Is professional and free of typos, slang, etc.<br> 3. Thoroughly explains the problem and the solution.<br> 4. Is understandable by the average person.|The problem statement is headed in the right direction. I sort of understand what you want the program to do but I suggest a bit more explanation as to what your program does. Does it allow you to store or edit or comment about video games? Does it do the things you asked with the questions, and how. |
|**Design Documentation**|1. Navigation/flow through the application is logical and easy to use. <br>2. The order in which values are displayed are logical and easy to understand/use <br>3. The order in which the form fields entered are logical and easy to understand/use<br>4. All data discussed/documented (problem statement, flow, db design, etc.) is represented on the screens. <br>5. Project plan and time log are up-to-date. |Pretty straight forward and good as directories are understandable. One thing is, your resource directory, did you want it to be called sample_resource?  |
|**Data model/Database**|1. Everything on the screens and problem statement/flow is represented in the model. <br> 2. There are at least two 1-to-many relationships.<br> 3. The model represents good database design. <br>|Db looks good. Like you suggested, potentially having ‘igdb’ explanation in your comments will help the programmers understand what it is. |
|**Code**|1. Proper Maven project structure is used. <br> 2. a .gitignore file for IntelliJ Java projects has been implemented. <br> 3. There is not any redundant or copy/paste code in the JSPs or classes.<br> 4. Classes are appropriately-sized (no monster classes).<br> Property files are used appropriately: no hard-coded values. <br> 5. Logging statements are used rather than System.out.println and printStackTrace (be sure to use a search to look for these!).<br> 6. There are appropriate unit tests/code coverage. |Most of your coding is good, everything seems pretty standard at this point with your Dao and entity files. No real suggestions on how to improve your coding. |

**Comment by kileader** [comment]
I agree that I should have a solution in the problem statement. I figured sample_resources was my own sort of way to hide personal info. I couldn't really get .sample things to work correctly with gitignore
